dataset_params:
  root_dir: /home/yuan/hdd/png
  meta_dir: /home/yuan/hdd/ldmk_out
  frame_shape: [256, 256, 3]
  augmentation_params:
    flip_param:
      horizontal_flip: True
      time_flip: False
    jitter_param:
      brightness: 0.1
      contrast: 0.1
      saturation: 0.1
      hue: 0.1

train_params:
  num_epochs: 50
  num_repeats: 2
  lr_tdmm: 2.0e-4
  batch_size: 64
  checkpoint_freq: 1
  loss_weights:
    landmark: 1
    tdmm_param: 1.0e-2
